apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: global-shared-assets-pvc # 最终在 API 请求中指定的 pvcName 名称
  namespace: default # 部署在工作空间所在的 namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: global-shared-assets-pv # 必须精确匹配创建的 PV 的 name
  storageClassName: "" # 静态绑定必须留空 ""，避免动态供给器干预
