apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  # annotations:
    # storageclass.kubernetes.io/is-default-class: "true" # Set as default storage class
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # Must match deployment's env PROVISIONER_NAME
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "true" # Retain deleted directories in archive instead of hard deleting
mountOptions:
  - nfsvers=3
  - nolock
  - tcp
  - noatime
  - noresvport
allowVolumeExpansion: true
