apiVersion: v1
kind: PersistentVolume
metadata:
  name: bocomwork-local-share-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/bocomwork-share
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bocomwork-local-share
  namespace: bocomwork
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: bocomwork-local-share-pv
  storageClassName: ""
